AWSTemplateFormatVersion: 2010-09-09
Description: To provision to ec2 instance
Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: Select VPC Security Group and Availability Zone
        Parameters:
          - pAzname
      - Label:
          default: Selecte Asubnet type  AppSubnetsIdMap eu-central-1
        Parameters:
          - pInstanceType

Parameters:
  pAzname:
    Description: Select AZ
    Type: 'AWS::EC2::AvailabilityZone::Name'
  
  pInstanceType:
    Description: "Select Instance Type"
    Type: String
    Default: "t2.micro"
    AllowedValues:
      - t2.nano
      - t2.micro
      - t2.small
Conditions:
  cSubnet1: !Equals [! eSubnsetzone1, pAzname]
  cSubnet2: !Equals [!importValue eSubnsetzone2, pAzname]


Resources:
  rTestEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: "ami-05548f9cecf47b442"
      InstanceType: !Ref pInstanceType
      NetworkInterfaces:
        - SubnetId: !importValue 
            Fn::If: [cSubnet1, eSubnsetid1, [cSubnet2, eSubnsetid2, "No Value"]]
          DeviceIndex: 0
          AssociatePublicIpAddress: false